In [156]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [157]:
df = pd.read_csv('../dataset/raw/Colombo-House-Dataset-3000.csv')
df.head()

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,STREET_NAME,FORMATTED_ADDRESS
0,Brokered by Real Mart,House for sale,"94,601,238",5,5,"5,938.49","Moratuwa, Colombo",Colombo,Moratuwa,Colombo,Moratuwa,NaN,"Moratuwa, Colombo"
1,Brokered by Property Solutions,House for sale,"46,044,725",3,3,"1,768.45","Homagama, Colombo",Colombo,Homagama,Colombo,Homagama,NaN,"Homagama, Colombo"
2,Brokered by Property Solutions,House for sale,"90,985,626",5,4,"5,063.38","Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,Colombo,Boralesgamuwa,NaN,"Boralesgamuwa, Colombo"
3,Brokered by Emil Realtors Pvt Ltd,House for sale,"28,967,644",3,2,"2,619.82","Piliyandala, Colombo",Colombo,Piliyandala,Colombo,Piliyandala,NaN,"Piliyandala, Colombo"
4,Brokered by Ideal Marketing,Villa for sale,"98,596,073",5,5,"4,914.25","Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,Colombo,Boralesgamuwa,NaN,"Boralesgamuwa, Colombo"

In [158]:
print(df.columns)

Index(['BROKERTITLE', 'TYPE', 'PRICE', 'BEDS', 'BATH', 'PROPERTYSQFT',
       'ADDRESS', 'STATE', 'MAIN_ADDRESS', 'ADMINISTRATIVE_AREA_LEVEL_2',
       'LOCALITY', 'STREET_NAME', 'FORMATTED_ADDRESS'],
      dtype='object')

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BROKERTITLE                  3000 non-null   object
 1   TYPE                         3000 non-null   object
 2   PRICE                        3000 non-null   object
 3   BEDS                         3000 non-null   int64
 4   BATH                         3000 non-null   int64
 5   PROPERTYSQFT                 3000 non-null   object
 6   ADDRESS                      3000 non-null   object
 7   STATE                        3000 non-null   object
 8   MAIN_ADDRESS                 3000 non-null   object
 9   ADMINISTRATIVE_AREA_LEVEL_2  3000 non-null   object
 10  LOCALITY                     3000 non-null   object
 11  STREET_NAME                  38 non-null     object
 12  FORMATTED_ADDRESS            3000 non-null   object
dtypes: int64(2), object(11)
memory usage: 304.8+ KB

In [160]:
print(df["PRICE"].dtype)
print(df["PROPERTYSQFT"].dtype)

object
object

In [161]:
df["PRICE"] = (
    df["PRICE"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(float)
)

df["PROPERTYSQFT"] = (
    df["PROPERTYSQFT"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(float)
)

print(df["PRICE"].dtype)
print(df["PROPERTYSQFT"].dtype)

float64
float64

In [162]:
# check for missing values
missing_values = df.isnull().sum()

print(missing_values)

BROKERTITLE                       0
TYPE                              0
PRICE                             0
BEDS                              0
BATH                              0
PROPERTYSQFT                      0
ADDRESS                           0
STATE                             0
MAIN_ADDRESS                      0
ADMINISTRATIVE_AREA_LEVEL_2       0
LOCALITY                          0
STREET_NAME                    2962
FORMATTED_ADDRESS                 0
dtype: int64

In [163]:
missing_percentage = (
    df.isnull().sum() / len(df) * 100
)

missing_table = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage": missing_percentage
})

missing_table

                             Missing Values  Percentage
BROKERTITLE                               0    0.000000
TYPE                                      0    0.000000
PRICE                                     0    0.000000
BEDS                                      0    0.000000
BATH                                      0    0.000000
PROPERTYSQFT                              0    0.000000
ADDRESS                                   0    0.000000
STATE                                     0    0.000000
MAIN_ADDRESS                              0    0.000000
ADMINISTRATIVE_AREA_LEVEL_2               0    0.000000
LOCALITY                                  0    0.000000
STREET_NAME                            2962   98.733333
FORMATTED_ADDRESS                         0    0.000000

In [164]:
df.drop(columns=['STREET_NAME'], inplace=True)

In [165]:
df.head()

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,FORMATTED_ADDRESS
0,Brokered by Real Mart,House for sale,94601238.0,5,5,5938.49,"Moratuwa, Colombo",Colombo,Moratuwa,Colombo,Moratuwa,"Moratuwa, Colombo"
1,Brokered by Property Solutions,House for sale,46044725.0,3,3,1768.45,"Homagama, Colombo",Colombo,Homagama,Colombo,Homagama,"Homagama, Colombo"
2,Brokered by Property Solutions,House for sale,90985626.0,5,4,5063.38,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,Colombo,Boralesgamuwa,"Boralesgamuwa, Colombo"
3,Brokered by Emil Realtors Pvt Ltd,House for sale,28967644.0,3,2,2619.82,"Piliyandala, Colombo",Colombo,Piliyandala,Colombo,Piliyandala,"Piliyandala, Colombo"
4,Brokered by Ideal Marketing,Villa for sale,98596073.0,5,5,4914.25,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,Colombo,Boralesgamuwa,"Boralesgamuwa, Colombo"

In [166]:
# duplicate raws

print(f"Number of duplicate rows: {df.duplicated().sum()}")

Number of duplicate rows: 3

In [167]:
df = df.drop_duplicates()

In [168]:
df.shape[0]

2997

### Numerical statistics

In [169]:
df.describe()

              PRICE         BEDS         BATH  PROPERTYSQFT
count  2.997000e+03  2997.000000  2997.000000   2997.000000
mean   8.620929e+07     4.244912     3.621622   3307.545506
std    8.551143e+07     1.663661     1.400567   1828.523152
min    5.500000e+06     1.000000     1.000000    500.000000
25%    3.323737e+07     3.000000     3.000000   1974.950000
50%    5.821799e+07     4.000000     3.000000   3083.410000
75%    1.078407e+08     5.000000     4.000000   4139.820000
max    8.500000e+08    10.000000    10.000000  15000.000000

In [170]:
# check for suspicious values in BEDS, BATH, PRICE, PROPERTYSQFT

print(f"Number of rows with BEDS <= 0: {len(df[df['BEDS'] <= 0])}")
print(f"Number of rows with BATH <= 0: {len(df[df['BATH'] <= 0])}")
print(f"Number of rows with PRICE <= 0: {len(df[df['PRICE'] <= 0])}")
print(f"Number of rows with PROPERTYSQFT <= 0: {len(df[df['PROPERTYSQFT'] <= 0])}")

Number of rows with BEDS <= 0: 0
Number of rows with BATH <= 0: 0
Number of rows with PRICE <= 0: 0
Number of rows with PROPERTYSQFT <= 0: 0

In [171]:
df['TYPE'].value_counts()

TYPE
House for sale    2826
Villa for sale     171
Name: count, dtype: int64

In [172]:
df['LOCALITY'].nunique()

38

In [173]:
print(df["LOCALITY"].value_counts().head(20))

LOCALITY
Thalawathugoda    163
Nugegoda          157
Colombo 7         153
Dehiwala          146
Moratuwa          140
Mount Lavinia     132
Pitakotte         132
Boralesgamuwa     131
Nawala            119
Kolonnawa         116
Wellampitiya      116
Battaramulla      112
Rathmalana        108
Maharagama         84
Homagama           83
Awissawella        82
Padukka            77
Kesbewa            75
Kottawa            70
Colombo 6          63
Name: count, dtype: int64

In [174]:
features = [
    "BEDS",
    "BATH",
    "PROPERTYSQFT",
    "TYPE",
    "LOCALITY"
]

target = "PRICE"

In [175]:
# remove unnecessary whitespaces from the column names
df = df.drop(
    columns=[
        "STREET_NAME",
        "BROKERTITLE",
        "MAIN_ADDRESS",
        "ADMINISTRATIVE_AREA_LEVEL_2",
        "STATE"
    ],
    errors="ignore"
)

In [176]:
df.to_csv(
    "../dataset/processed/cleaned_house_prices.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.